---
title: "Make your tables here"
author: "Katherine Heal"
date: "January 10 2020"
output: html_document
---
#TO DO: update these with better names for the compounds (two versions of names for all supplemental tables)
#TO DO: make it so we can compile all the supplemental tables into one excel file
#TO DO: add more supplemental tables

```{r setup, include=FALSE}
library(tidyverse)
library(cowplot)
library(here)
```

#Supp tables (LATEX files)
```{r, error = FALSE, warning=FALSE, message=FALSE}
#Enviro Sample Descriptions
source('Tables/Code/Sample_Descriptions.R')
remove(list = ls())

#Phyto Sample Descriptions 
source('Tables/Code/Culture_descriptions.R')
remove(list = ls())

#Phyto Sample Descriptions 
source('Tables/Code/Enviro_Description.R')
remove(list = ls())


```


#Supplemental Tables (CSVs)
```{r, error = FALSE, warning=FALSE, message=FALSE}
#Full culture sample descriptions
source('Tables/Code/Culture_descriptions_full.R')
remove(list = ls())

#MF_cluster_assigments - known compounds and which clusters 
source('Tables/Code/MFCluster_Assignments.R')
remove(list = ls())

#Summary of PC and quantifiable metabolites
source('Tables/Code/total_quantmetab_and_PC.R')
remove(list = ls())

#Full environmental sample descriptions
source('Tables/Code/full_enviro_sample_descriptions.R')
remove(list = ls())

#Summary of quantification methods used
source('Tables/Code/full_quan_methods_table.R')
remove(list = ls())

#All mass features and normalized peak areas
source('Tables/Code/full_EnviroCulture_PeakArea_results.R')
remove(list = ls())

#Full quantified results for enviro samples
source('Tables/Code/full_quan_enviro_results_table.R')
remove(list = ls())

#Full quantified results for culture samples
source('Tables/Code/full_quan_culture_results_table.R')
remove(list = ls())

#Summary of quantification methods used
source('Tables/Code/full_quan_methods_table.R')
remove(list = ls())

####Checked up to here














```

#Merge all the csv files into one big xcel file here
```{r, error = FALSE, warning=FALSE, message=FALSE}
library(XLConnect) #requires Java between 8 and 11
file.remove("Tables/Manuscript_tables/SuppTables/Combined_SuppTables.xlsx")

#write out the order of the tables you want
supp.tables <- 
  c("Tables/Manuscript_tables/SuppTables/Culture_descriptions_full.csv",
    "Tables/Manuscript_tables/SuppTables/MFCluster_Assignments.csv",
    "Tables/Manuscript_tables/SuppTables/Total_QuanMetabandPC.csv",
    "Tables/Manuscript_tables/SuppTables/Full_Enviro_Samp_Descriptions.csv",
    "Tables/Manuscript_tables/SuppTables/Full_EnviroCulture_PeakAreas.csv", 
    "Tables/Manuscript_tables/SuppTables/Full_Quan_Enviro_Results.csv",
    "Tables/Manuscript_tables/SuppTables/Full_Quan_Culture_Results.csv",
    "Tables/Manuscript_tables/SuppTables/Full_Quan_Methods.csv",
    "RawOutput/QC_parameters.csv")

files.nms <- basename(supp.tables) %>% str_remove(".csv") %>%
  str_remove("Tables/Manuscript_tables/SuppTables/") %>%
  str_remove("RawOutput/")

files.nms.2 <- files.nms %>% as.data.frame() %>%
  mutate(try = paste0("Table S", row_number()+3))

f.out <- "Tables/Manuscript_tables/SuppTables/Combined_SuppTables.xlsx"
wb <- loadWorkbook(f.out, create=TRUE)

for (i in 1:length(supp.tables)) {
  ## ingest the CSV file
  temp_DT <- read_csv(supp.tables[[i]])

  ## Create the sheet where the file will be outputed to 
  createSheet(wb, name=files.nms[i])

  ## output the csv contents
  writeWorksheet(object=wb, data=temp_DT, sheet=i, header=TRUE, rownames=NULL)
}

saveWorkbook(wb)
remove(list = ls())

```
